#!/bin/bash

######### convert a list of extracted and pre-formated (advertising-)hosts to dnsmasq format

# use the whole line and mark it as a pattern, then put the matched pattern into the new context

sed 's:\(^.*$\):address=\/\1\/127.0.0.1:' $1
